#!/bin/zsh

_serve() {
  local interrupted="0"

  signal_interrupt() {
    interrupted="1"
  }

  trap signal_interrupt SIGINT

  serve -n &
  local pid_serve=$!

  local files_watched=(alic2.css alic2.js index.html)
  local time_update="$(stat -c %Z ${files_watched})"
  local time_update_previous="${time_update}"

  while [[ ${interrupted} == "0" ]] ; do
    time_update=$(stat -c %Z ${files_watched})

    if [[ "${interrupted}" == "0" && "${time_update}" != "${time_update_previous}" ]] {
      printf "modification_detected->{reserving}\n"

      time_update_previous="${time_update}"

      kill ${pid_serve}

      serve -n &
      pid_serve=$!
    }

    sleep 0.1s
  done

  kill ${pid_serve}
  sleep 0.1s
}

_serve $@
